before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal
language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ./manage.py test # or py.test for Python versions 3.5 and below

