services:
  - postgresql
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install gdal-bin -y
  - psql -c "CREATE USER group1 WITH PASSWORD '1';" -U postgres
  - psql -c "CREATE DATABASE group1;" -U postgres
  - psql -c "GRANT ALL ON DATABASE group1 TO group1;" -U postgres
  - psql -U postgres -c "create extension postgis"
language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ./manage.py makemigrations
  - ./manage.py makemigrations api
  - ./manage.py migrate
  - ./manage.py test # or py.test for Python versions 3.5 and below

